name: velyvelo
description: VelyVelo is a French company that offers electric bike rental.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 2.4.1+19

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Map view
  flutter_map: ^4.0.0
  flutter_map_marker_cluster: ^1.1.1
  latlong2: ^0.8.0

  # Services & State management
  http: ^0.13.4
  get: ^4.6.1
  flutter_riverpod: ^2.4.9
  path_provider: ^2.0.8
  shared_preferences: ^2.0.13
  firebase_messaging: ^14.3.0
  url_launcher: ^6.0.20
  firebase_core: ^2.8.0
  logger: ^2.0.2+1

  # Flutter actions
  pull_to_refresh: ^2.0.0
  image_picker: ^1.0.5
  mobile_scanner: ^3.5.5

  # Styles
  dotted_border: ^2.0.0+2
  dropdown_search: ^5.0.6
  cupertino_icons: ^1.0.2
  carousel_slider: ^4.0.0
  colorful_safe_area: ^1.0.0
    
  # Others
  shimmer: ^3.0.0
  flutter_native_splash: ^2.0.2
  qr_flutter: ^4.0.0
  camera: ^0.10.5+7
  image_gallery_saver: ^2.0.3
  cached_network_image: ^3.2.1
  upgrader: ^8.4.0

  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  mocktail: ^1.0.2

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"

flutter_native_splash:
  color: "#131314"
  image: "assets/logo_splash_bigger.png"
  
flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/pins/

  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Black.ttf
        - asset: fonts/Montserrat-Bold.ttf
        - asset: fonts/Montserrat-ExtraBold.ttf
        - asset: fonts/Montserrat-ExtraLight.ttf
        - asset: fonts/Montserrat-Italic.ttf
        - asset: fonts/Montserrat-Light.ttf
        - asset: fonts/Montserrat-Medium.ttf
        - asset: fonts/Montserrat-Regular.ttf
        - asset: fonts/Montserrat-SemiBold.ttf
        - asset: fonts/Montserrat-Thin.ttf
