name: Flutter Integration Tests
on: [push, pull_request]

jobs:
  test:
      name: Testing iOS app
      runs-on: macOS-latest
      steps:
        - name: Checkout repository
          uses: actions/checkout@v1
        - name: Force XCode 11.3
          run: sudo xcode-select -switch /Applications/Xcode_11.3.app
        # - name: Testing Swift package
        #   run: exec ./.github/scripts/test_swift_package.sh
        - name: Testing iOS app
          run: flutter test integration_test/main_test.dart
#   flutter_integration_test:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       - uses: actions/setup-java@v1
#         with:
#           java-version: "12.x"
#       - uses: subosito/flutter-action@v1
#         with:
#           channel: "stable"
#       - run: flutter pub get
# #       - run: flutter analyze
#       - run: flutter test integration_test/main_test.dart -d chrome
